version: '3'
services:
  api:
    image: "bluevelvet-api"
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/db_name?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      - SPRING_DATASOURCE_USERNAME=bluevelvet
      - SPRING_DATASOURCE_PASSWORD=bluevelvet
    depends_on:
      - database
  database:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=blue-velvet
      - MYSQL_USER=bluevelvet
      - MYSQL_PASSWORD=bluevelvet
      - MYSQL_ROOT_PASSWORD=bluevelvet
